#!/usr/bin/env bash

set -euo pipefail

echo "Running git-shallow-clone-buildkite-plugin -- pre-checkout"

ARGS=""

# order of precedence
INCLUDE="${BUILDKITE_PLUGIN_GIT_SHALLOW_CLONE_INCLUDE:-}"
DEPTH="${BUILDKITE_PLUGIN_GIT_SHALLOW_CLONE_DEPTH:-1}"

# ensure we match a git sha
if [[ "${INCLUDE}" =~ ^[0-9a-f]{5,40}$ ]]
then
  ARGS="--shallow-exclude ${INCLUDE}~1"
else
  ARGS="--depth ${DEPTH}"
fi

export BUILDKITE_GIT_CLONE_FLAGS="-v ${ARGS}"
export BUILDKITE_GIT_FETCH_FLAGS="-v --prune ${ARGS}"

#export BUILDKITE_GIT_CLONE_FLAGS="-v --filter=blob:none"
