#!/usr/bin/env bash

set -euo pipefail

echo "Running git-shallow-clone-buildkite-plugin -- pre-checkout"

ARGS=""

# order of precedence
SINCE="${BUILDKITE_PLUGIN_GIT_SHALLOW_CLONE_SINCE:-}"
DEPTH="${BUILDKITE_PLUGIN_GIT_SHALLOW_CLONE_DEPTH:-1}"

# ensure we match a git sha
if [[ "${SINCE}" =~ ^[0-9]+$ ]]
then
  ARGS="--shallow-since ${SINCE}~1"
else
  ARGS="--depth ${DEPTH}"
fi

export BUILDKITE_GIT_CLONE_FLAGS="-v ${ARGS}"
export BUILDKITE_GIT_FETCH_FLAGS="-v --prune ${ARGS}"

#export BUILDKITE_GIT_CLONE_FLAGS="-v --filter=blob:none"
